name: ec2-deploy

on:
  workflow_call:

jobs:
  deploy_on_ec2:
    runs-on: ubuntu-latest
    # env:
    #   DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
    #   DOCKER_TAG: ${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: scp to server for copy a file
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          source: "."
          target: "/home/ubuntu/"

      - name: ssh to  server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export DOCKERHUB_USERNAME=${{secrets.DOCKERHUB_USERNAME}} 
            export TAG=${{secrets.github.sha}}
            echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            mkdir -p /home/ubuntu/app
            cp -r  /home/ubuntu/*  /home/ubuntu/app
            cd /home/ubuntu/app

            chmod +x docker-download.txt
            ./docker-download.txt
            docker compose stop
            docker compose rm -f
            docker compose pull
            docker compose up -d --force-recreate