# name of the workflow
name: my_details
on: 
  push:
    branches:
      -main
jobs:
  personal_detail:
    runs-on: ubuntu-latest

    steps:
      name: personal details
      run: echo "My name is  harsh"

  college_detail:
    runs-on: ubuntu-latest
    steps:
      name: college info
      run: echo "I am from NSIT "
  
      
